services:
  mysql-dev:
    container_name: ${LZ}_orion_db_${ORION_ENV}
    image: mysql:5.7.44
    restart: unless-stopped
    env_file:
      - orion/env/${ORION_ENV}.env
    volumes:
      - ./database/data/${ORION_ENV}:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3305:${MYSQL_PORT}"
    networks:
      - gs_network_${ORION_ENV}
  orion-web-dev:
    container_name: ${WEB_URL}
    image: aleonard9/orion-web:${ORION_ENV}
    restart: unless-stopped
    env_file:
      - orion/env/${ORION_ENV}.env
    ports:
      - "79:80"
    depends_on:
      - mysql-dev
    links:
      - mysql-dev
    networks:
      - gs_network_${ORION_ENV}
  orion-cf-tunnel-dev:
    container_name: orion_cloudflared_tunnel_${ORION_ENV}
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --pq run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - gs_network_${ORION_ENV}
networks:
  gs_network_dev: 
    external: true