services:
  mysql-local:
    image: mysql:5.7.44
    env_file:
      - orion/env/test.env
    container_name: gs_orion_db_test
    volumes:
      - orion_backup_volume_test:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
    - "3303:3306"
drivers:
  orion_backup_volume:
    name: orion_backup_volume_test
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.238:5000,username=orion,password=abc123,nolock,soft,rw"
      device: ":/docker/example"