version: "3"

services:
  mysql-dev:
    image: mysql:5.7.29
    container_name: orion_db
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: orion
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  orion-web:
    image: aleonard9/orion-web
    container_name: orion_web
    ports:
      - "8000:80"
    env_file:
      - orion/dev.env
    tty: true
    depends_on:
      - mysql-dev
    links:
      - mysql-dev
  phoenxi-web:
    build: orion/.
    # image: aleonard9/orion-web:dev
    container_name: phoenix_web
    ports:
      - "80:80"
    env_file:
      - orion/dev.env
    tty: true
    depends_on:
      - mysql-dev
    links:
      - mysql-dev
